# Context {#context}

It is of interest of government organizations such as the Forest Inventory and Analysis Program (FIA) to be able to have reliable estimates of forest attributes in small domains such as ecological subsections (often refered to as ecosubsections) or counties. In particular, the FIA would like to have estimates with low variance in ecological subsections, however, the FIA only samples a small numbers of plots in these small areas. The research goal of this thesis is to address this problem by using techniques which seek to minimize variance of estimates while only introducing a small amount of bias. Having precise estimates of forest attributes at the ecosection level is crucial for educational programs and implementation of programs which seek to maintain the health of our forests. 

There are are wide range of techniques that can be used to address the problem of estimation of forest attributes. Broadly, these methods fall into three categories: direct estimators, indirect estimators, and model-based estimators. These are all methods of small area estimation. Direct estimators are those that rely only on the samples within the small area which we would like to measure. Some examples of a direct estimator are the mean of a variable, or the post-stratified estimate of a variable. These estimates do not rely on information outside of the small area being estimated, nor any auxilary information or data to produce their estimates. The second kind of estimator, indirect estimators, rely on data outside of the area of interest to produce their estimate, however they do not rely on auxilary data. With indirect estimators, we can use information (or "borrow strength") from nearby small areas to help improve our estimate in our area of interest. Finally, model-based estimators are those which both borrow strength from other small areas and use auxilary information to compute the estimate of interest. Within the category of model-based estimators, there are two classes, unit-level and area-level models. Unit-level models consider information at the level of which the data was collected. Area-level models consider information that has been aggregated to the level of a small area before the model is fit to the data. 

A small area estimation technique that has been increasing in popularity in the realm of applications to the FIA and forestry data in general is model-based estimation. As the FIA requires less variance in their estimates of increasingly smaller areas, it becomes inevitable that borrowing strength from surrounding areas and the use of auxilary data is needed to maintain a satisfactory amount of precision. To implement these models, there are two statistical schools of thought: frequentist methods and Bayesian methods. Frequentist models are the most common for estimation of forest attributes in small area estimation [CITE LOTS OF PAPERS HERE]. However, Bayesian methods have been used at the area-level for small area estunation of of forest attributes [@ver2017]. While frequentist methods are often viewed as the "default" method for doing small area estimation, there are many benefits of tackling these problems from a Bayesian perspective. Notably, Bayesian estimation utilizes prior distributions which allow us to quantify our prior uncertainty about the values of each parameter. 

This thesis compares the hierarchical Bayesian unit- and area-level models to small area estimation techniques already commonly used such as the Fay-Herriot model, EBLUP, post-stratification, and other techniques. By applying these models on four response variables across the entire Interior West, we can add a great deal of understanding to the usefulness of hierarchical Bayesian models in a small area estimation context, especially when considering its usefullness to the FIA and other forestry organizations. We only have been able to source one paper which uses hierarhical Bayesian modeling for small area estimation with a forestry application, and they only consider the area-level model with a particular response variable in particular forest [@ver2017]. This thesis thus adds significantly to our understanding of the usefulness of hierarchical Bayesian small area estimation in a forestry setting due to the introduction of the unit-level model, the vast number of response variables studied, and the vast range of area where we test the usefulness of this model. 

<!-- *provides background material on the topic and other approaches, and identifies what is added by this thesis* -->