# Discussion

## Findings and Takeaways

We have introduced, fit, and presented the results of six small area estimators across the Interior West with four forestry-related response variables. Particularly, we introduce two estimators which are uncommon in forestry research: the hierarchical Bayesian unit- and area-level estimators. The area-level hierarchical Bayesian estimator reduces variance in estimates significantly compared to common direct estimators, frequentist model-based approaches (EBLUPs), and the unit-level hierarchical Bayesian estimator. We see reduction in variance compared to the area-level frequentist estimator and post-stratification in the great majority of small areas when implementing the hierarchical Bayesian area-level estimator. In extremely non-forested small areas, the hierarchical Bayesian area-level estimator consistently has higher variance than post-stratification or the area-level EBLUP. This is likely due to the way in which the area-level hierarchical Bayesian estimator borrows strength. 

## Limitations 

## Possible Extensions

Now we turn to possible extensions to the work which has been done in this thesis. We explore ideas for further research on adjacent topics and possibilities for applying these methods in other locations. 

First, attempting to understand the performance of these hierarchical Bayesian estimators outside of the Interior West region of the United States through implementing these methods across the country would be insightful to the generalization of these estimators. Outside of the Interior West, the Forest Inventory and Analysis Programs has research stations in the Pacific Northwest region, Northern region, and Southern region. The hierarchical Bayesian area-level estimator is also a great candidate for estimation in Alaska. The reasons for its great candidacy are twofold: first, it is expensive and difficult to send foresters to collect data in Alaska due to the extreme rurality of the area; second, Alaska is very forested and we thus would likely see a large reduction in variance of estimates when using the hierarchical Bayesian area-level estimator. The area-level hierarchical Bayesian estimator reduced variance in forested areas quite well, and applying this technique to data in Alaska could help mitigate our smaller sample size. 

Another possibility for extending the research done in this thesis would be to adapt these hierarchical Bayesian estimators to produce estimates with lower variance under a variety of conditions. First, an implementation of a hybrid estimator could mitigate high variance in heavily non-forested areas. A hybrid estimator including both area-level model-based estimators which relies on the EBLUP's estimates in less-forested areas and the hierarchical Bayesian's estimates in more forested areas might result in lower variance across the board. The small areas in which the area-level hierarchical Bayesian estimator had higher variance than the area-level EBLUP were clearly non-random. A further analysis of these areas could lead to an insightful weighting system for this hybrid estimator. Another approach to mitigating the high variance seen in some eco-subsections for the area-level hierarchical Bayesian model would be to borrow strength differently, either through an explicit spatial analysis or by borrowing less strength (potentially to the eco-section level). Either of these methods could help weight areas closer to the eco-subsection of interest higher, potentially avoiding borrowing strength "too far out" that is potentially not strongly correlated with values in the eco-subsection of interest. Another way to mitigate this problem would be to introduce new auxiliary data. Auxiliary data which classifies the proportion of each eco-subsection that is a desert may help reduce variance in the more heavily deserted eco-subsections. 

An approach to understanding the performance of these hierarchical Bayesian estimators would be to create a simulation study where data is generated from known distributions. This allows us to know the parameter values of $\mu_{y_j}$, and we could better quantify the bias introduced by these estimators. This would be a great research project for a thesis student and would greatly help in the understanding of the overall performance of these estimators. 

Finally, another large project worth exploring would be to embark on the development, testing, and documenting of a new R software package which allows for more flexible hierarchical Bayesian small area estimators. The package used in this thesis, `hbsae`, has some nice features such as its speed due to the use of numerical integration rather than sampling from the posterior using Markov Chain Monte Carlo methods. However, this limits our functional forms of the distributions used in the estimators. With `hbsae` we are limited to Inverse-Gamma distributions on the prior for variability, and more importantly: Gaussian response. The unit-level hierarchical Bayesian estimator may produce estimates with lower variance given that we model its response variable as something right-skewed: potentially either a Gamma distribution or a Tweedie distribution. The Tweedie distribution is often used for data which is zero-inflated and is often used for generalized linear modeling [@jorgensen1997theory]. These attributes make it a great candidate for modeling the response variable of unit-level estimators. Outside of gaining flexibility, implementing new software with better documentation, consistent updates/patches, and a user-friendly manual would allow for researchers to implement these hierarchical Bayesian small area estimators more broadly and with ease. 