---
title: |- 
  A Hierarchical Bayesian Approach to 
  
  Small Area Estimation of Forest Attributes
author: 'Grayson White'
date: 'May 2021'
institution: 'Reed College'
division: 'Mathematical and Natural Sciences'
advisor: 'Kelly McConville' 
department: 'Mathematics - Statistics'
degree: 'Bachelor of Arts'
knit: bookdown::render_book
site: bookdown::bookdown_site
params:
  'Install needed packages for {thesisdown}': True
output: 
  thesisdown::thesis_pdf: default
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines(here::here("prelims", "00-abstract.Rmd")), collapse = "\n  ")`
# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab 
# is needed on the line after the `|`.
acknowledgements: |
  This is where acknowledgements will go. 
dedication: |
  To my family. 
# preface: |
#   This is an example of a thesis setup to use the reed thesis document class 
#   (for LaTeX) and the R bookdown package, in general.
# Specify the location of the bibliography below
bibliography: bib/thesis.bib
# Download your specific csl file and refer to it in the line below.
csl: csl/apa.csl
lot: true
lof: true
---
```{r include_packages, include=FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis.
if (!require(remotes)) {
  if (params$`Install needed packages for {thesisdown}`) {
    install.packages("remotes", repos = "https://cran.rstudio.com")
  } else {
    stop(
      paste('You need to run install.packages("remotes")",
            "first in the Console.')
    )
  }
}
if (!require(thesisdown)) {
  if (params$`Install needed packages for {thesisdown}`) {
    remotes::install_github("ismayc/thesisdown")
  } else {
    stop(
      paste(
        "You need to run",
        'remotes::install_github("ismayc/thesisdown")',
        "first in the Console."
      )
    )
  }
}
library(thesisdown)
# Set how wide the R output will go
options(width = 70)
```


```{r eval=!knitr::is_latex_output(), child=here::here("prelims", "00--prelim.Rmd")}

```

```{r eval=!knitr::is_latex_output(), child=here::here("prelims", "00-abstract.Rmd")}

```

<!-- # Introduction {.unnumbered} -->

<!-- National forest inventories such as the United States Forest Inventory and Analysis Program (FIA) monitor the status of a nation's forests by collecting data and estimating forest attributes such as basal area, above-ground biomass, tree count per acre, and net volume. Due to the sheer amount of forests in the United States, the FIA cannot collect the population data for these variables. Instead, they use a sampling design intended and well-suited for estimation of these variables over large geographic regions. This sampling design works very well for estimation of forest attributes in large regions and maintains a reasonable cost of employing foresters to collect the samples. While this method works sufficiently for large areas, it has become an interest of national forest inventories such as the FIA to be able to provide reliable and efficient estimates of forest attributes in small domains such as ecological subsections (often referred to as eco-subsections) and counties. In particular, the FIA would like to have estimates for the mean of these response variables with low variance in eco-subsections, however, the FIA only samples a small numbers of plots in these small areas. Currently, the FIA's standard approach to this problem is by using post-stratification. Post-stratification uses a weighted average of the forest attribute of interest and corrects for over- or under-sampling of forested land in the small area. While this estimator is unbiased and has lower variance than the sample mean, it does not reduce the variance enough for precise estimation at the eco-subsection level. The research goal of this thesis is to address this problem by using techniques which seek to minimize estimate variance while only introducing a small amount of bias.  -->

<!-- Having low variance estimates of forest attributes at the eco-subsection level is crucial for educational programs, implementation of programs which seek to maintain the health of our forests, and a number of other reasons: "FIA is responsible for reporting on dozens, if not hundreds, of forest attributes relating to merchantable timber and other wood products, fuels and potential fire hazard, condition of wildlife habitats, risk associated with fire, insects or disease, biomass, carbon storage, forest health, and other general characteristics of forest ecosystems" [@mcconville2020]. The ability to provide relevant information related to the listed forest attributes to land owners is reliant on the ability to attain low variance estimates of forest attributes on that land. Estimates with high variance often times do not allow for enough knowledge to be gained about the forest attributes of interest. Maintenance of these forested areas is crucial for preventing wildfires within small areas and for the surrounding area. Thus, it is important to inform private land owners of steps that must be taken to maintain the safety of their forested land and the surrounding land. Not only do wildfires cause damage to the trees in which they burn, but they also cause countless animals to lose their homes every year. These concerns, along with other risks related to the forest attributes listed above are the motivation to continue to strive for low variance estimates of forest attributes.  -->

<!-- This thesis is a study on how to reduce variance of our forest attribute estimates further through the mechanism of hierarchical Bayesian estimators. In order to introduce, study, and implement these estimators we approach the research through the following organization of ideas: -->

<!-- * The remainder of Chapter \@ref(context) discusses current common approaches for estimation of forest attributions. We also introduce less common approaches to performing this estimation, such as the hierarchical Bayesian approach. We introduce the idea of borrowing strength and discuss how different estimators borrow strength. -->
<!-- * Chapter \@ref(data) introduces the data used to accomplish our research goal. We discuss the nested structure of the data and how it lends itself to hierarchical modeling. We explore the spatial aspects of our response variables and the distributions of these variables. We also introduce the data used for our explanatory variable and the data used for strata weighting. -->
<!-- * Chapter \@ref(methods) builds up the theory and mathematics behind the estimators used in this thesis. Starting at the simplest case of the sample mean, we progressively introduce new estimators which take varying levels of information into account. We also introduce some theory regarding Bayesian statistics in order to build intuition for our hierarchical Bayesian estimators. -->
<!-- * Chapter \@ref(results) showcases the results of each estimator's performance. We discuss strengths and weaknesses of estimators implemented. These results are explored spatially and we gain insight into regions where particular estimators reduce variance more than others. -->
<!-- * Chapter \@ref(discussion) discusses the key findings of this thesis, the limitations regarding these findings, and possible extensions of the work done in this thesis. -->

