---
title: "Full Modeling of Interior West"
author: "Grayson White"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Intro
This document contains the code for the five types of models used for comparison in this thesis: direct post-stratified estimator, area-level frequentist model, area-level hierarchical Bayesian model, unit-level frequentist model, and unit-level hierarchical Bayesian model. 

## Load data
```{r load_data, message = FALSE, warning = FALSE}
intwest <- read_csv("../data/subsets/dat_small.csv")
tccpop <- read_csv("../data/population/tcc_pop.csv")
strata <- read_csv("../data/population/strata.csv")
```

## Source modeling functions
```{r modeling_fcns}
source("../modeling-functions/direct_CoV.R")
source("../modeling-functions/direct_estimate.R")
source("../modeling-functions/freq_area.R")
source("../modeling-functions/freq_area_CoV.R")
source("../modeling-functions/freq_unit.R")
source("../modeling-functions/freq_unit_CoV.R")
source("../modeling-functions/hb_area.R")
source("../modeling-functions/hb_CoV.R")
source("../modeling-functions/hb_unit.R")
```


