---
title: "Thesis Results"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mase)
library(hbsae)
library(sae)
```

## Data
### Loading
```{r load_data, message = FALSE, warning = FALSE}
intwest <- read_csv("../data/subsets/df.csv")
tccpop <- read_csv("../data/population/tcc_pop.csv")
strata <- read_csv("../data/population/strata.csv")
```

### Cleaning

Set up strata:
```{r clean_data, message = FALSE, warning = FALSE}
intwest <- intwest %>%
  mutate(FIAstrat = case_when(
    FIAstrat == "1" ~ "Sampled-Forest",
    FIAstrat == "2" ~ "Sampled-Nonforest",
    FIAstrat == "0" ~ "Sampled-Nonforest",
    FIAstrat == "3" ~ "Sampled-Nonforest",
  )) 
```

Initial data changes to avoid horrific errors:
```{r}
no0_subsections <- intwest %>%
  group_by(subsection) %>%
  summarize(mean_y = mean(BIOLIVE_TPA),
            mean_x = mean(nlcd11)) %>%
  filter(mean_y > 0 & mean_x > 0) %>% # remove subsections that only contain 0 
  dplyr::select(subsection) %>%
  pull()

intwest_no0 <- intwest %>%
  filter(subsection %in% no0_subsections) %>%
  filter(!(province %in% c("M261", "M334", # two & three eco-subs each, divergent integrals
                           "331", "341", "342"))) # tiny amount of forests, error in area-level
```

List of dataframes:
```{r}
iw <- split(intwest_no0, f = intwest_no0$province)


# iw5_subsections <- iw[[5]] %>%
#   group_by(subsection) %>%
#   summarize(mean = mean(BIOLIVE_TPA)) %>%
#   filter(mean > 3) %>%
#   dplyr::select(subsection) %>%
#   pull()
# 
# iw[[5]] <- iw[[5]] %>%
#   filter(subsection %in% iw5_subsections)
# 
# iw6_subsections <- iw[[6]] %>%
#   group_by(subsection) %>%
#   summarize(mean = mean(BIOLIVE_TPA)) %>%
#   filter(mean > 3) %>%
#   dplyr::select(subsection) %>%
#   pull()
# 
# iw[[6]] <- iw[[6]] %>%
#   filter(subsection %in% iw6_subsections)
# 
# iw7_subsections <- iw[[7]] %>%
#   group_by(subsection) %>%
#   summarize(mean = mean(BIOLIVE_TPA)) %>%
#   filter(mean > 3) %>%
#   dplyr::select(subsection) %>%
#   pull()
# 
# iw[[7]] <- iw[[7]] %>%
#   filter(subsection %in% iw7_subsections)
# 
# intwest_no0 <- bind_rows(iw)
```

## Modeling

### Source modeling functions
```{r modeling_fcns}
source("../modeling-functions/direct_CoV.R")
source("../modeling-functions/direct_estimate.R")
source("../modeling-functions/freq_area.R")
source("../modeling-functions/freq_unit.R")
source("../modeling-functions/freq_unit_CoV.R")
source("../modeling-functions/hb_area.R")
source("../modeling-functions/hb_CoV.R")
source("../modeling-functions/hb_unit.R")
```

### Post-stratification and the mean

```{r postStrat, message = FALSE}
strata <- strata %>%
  filter(zoneid %in% unique(intwest_no0$subsection)) %>%
  mutate(
    fnf_no_water = case_when(
      fnf_no_water == 1 ~ "Sampled-Forest",
      fnf_no_water == 2 ~ "Sampled-Nonforest"
    )
  )
strata <- strata %>%
  dplyr::select(-zoneprop)

# split strata into list and drop column split by
strata_list <- lapply(split(strata, f = strata$zoneid), function(strata) { strata$zoneid <- NULL; strata})

# split subsections into list
subsection_list <- split(intwest_no0, intwest_no0$subsection)

postStrat2_bio <- function(data, strata) {
  est <- mase::postStrat(y = data[["BIOLIVE_TPA"]],
                  x_sample = data[["FIAstrat"]],
                  x_pop = strata,
                  data_type = "totals",
                  var_est = T)
  return(data.frame(ps_est = est$pop_mean, sd = sqrt(est$pop_mean_var)))
}
postStrat2_ba <- function(data, strata) {
  est <- mase::postStrat(y = data[["BALIVE_TPA"]],
                  x_sample = data[["FIAstrat"]],
                  x_pop = strata,
                  data_type = "totals",
                  var_est = T)
  return(data.frame(ps_est = est$pop_mean, sd = sqrt(est$pop_mean_var)))
}

postStrat2_voln <- function(data, strata) {
  est <- mase::postStrat(y = data[["VOLNLIVE_TPA"]],
                  x_sample = data[["FIAstrat"]],
                  x_pop = strata,
                  data_type = "totals",
                  var_est = T)
  return(data.frame(ps_est = est$pop_mean, sd = sqrt(est$pop_mean_var)))
}

postStrat2_cnt <- function(data, strata) {
  est <- mase::postStrat(y = data[["CNTLIVE_TPA"]],
                  x_sample = data[["FIAstrat"]],
                  x_pop = strata,
                  data_type = "totals",
                  var_est = T)
  return(data.frame(ps_est = est$pop_mean, sd = sqrt(est$pop_mean_var)))
}

postStrat2_x <- function(data, strata) {
  est <- mase::postStrat(y = data[["nlcd11"]],
                  x_sample = data[["FIAstrat"]],
                  x_pop = strata,
                  data_type = "totals",
                  var_est = T)
  return(data.frame(ps_est_x = est$pop_mean))
}

post_strat_bio <- map2(.x = subsection_list, .y = strata_list, .f = postStrat2_bio)
post_strat_ba <- map2(.x = subsection_list, .y = strata_list, .f = postStrat2_ba)
post_strat_voln <- map2(.x = subsection_list, .y = strata_list, .f = postStrat2_voln)
post_strat_cnt <- map2(.x = subsection_list, .y = strata_list, .f = postStrat2_cnt)
post_strat_x <- map2(.x = subsection_list, .y = strata_list, .f = postStrat2_x)

results <- data.frame(
  ps_est = c(bind_rows(post_strat_bio)$ps_est,
             bind_rows(post_strat_ba)$ps_est,
             bind_rows(post_strat_cnt)$ps_est,
             bind_rows(post_strat_voln)$ps_est),
  ps_x = rep(bind_rows(post_strat_x)$ps_est_x, 4),
  ps_sd = c(bind_rows(post_strat_bio)$sd,
             bind_rows(post_strat_ba)$sd,
             bind_rows(post_strat_cnt)$sd,
             bind_rows(post_strat_voln)$sd),
  subsection = rep(names(post_strat_bio), 4),
  response = c(
    rep("BIOLIVE_TPA", length(post_strat_bio)),
    rep("BALIVE_TPA", length(post_strat_ba)),
    rep("CNTLIVE_TPA", length(post_strat_cnt)),
    rep("VOLNLIVE_TPA", length(post_strat_voln)))
)
```

```{r mean}
dirmean <- list()
dirmean[1:length(iw)] <- lapply(iw,
                                direct_estimate,
                                response = "BIOLIVE_TPA", 
                                "subsection")
dirmean[(length(iw)+1):(2*length(iw))] <- lapply(iw,
                                                 direct_estimate,
                                                 response = "BALIVE_TPA",
                                                 "subsection")
dirmean[(2*length(iw) + 1):(3*length(iw))] <- lapply(iw,
                                                     direct_estimate,
                                                     response = "CNTLIVE_TPA",
                                                     "subsection")
dirmean[(3*length(iw) + 1):(4*length(iw))] <- lapply(iw,
                                                     direct_estimate,
                                                     response = "VOLNLIVE_TPA",
                                                     "subsection")

dir <- bind_rows(dirmean) %>%
  dplyr::select(Domain, Direct, CV) %>%
  mutate(cov_dirmean = CV / 100) %>%
  rename(est_dirmean = Direct) %>%
  dplyr::select(-CV) %>%
  mutate(response = c(
    rep("BIOLIVE_TPA", length(post_strat_bio)),
    rep("BALIVE_TPA", length(post_strat_ba)),
    rep("CNTLIVE_TPA", length(post_strat_cnt)),
    rep("VOLNLIVE_TPA", length(post_strat_voln))))

results <- results %>%
  left_join(dir, by = c("subsection" = "Domain",
                        "response" = "response"))
```

```{r dataframe-cleanup}
# Create CoV for ps-estimator
results <- results %>%
  mutate(
    cov_dirps = ps_sd / est_dirmean
  )

# change names and rearrange 
results <- results %>%
  rename(est_dirps = ps_est,
         sd_dirps = ps_sd) %>%
  relocate("subsection", "response", "est_dirps", "cov_dirps")
```

```{r}
# set up list for area level models
ps_dat <- results %>%
  dplyr::select(est_dirps, sd_dirps, ps_x, subsection, response) %>%
  dplyr::mutate(var = sd_dirps^2) %>%
  dplyr::rename(est = est_dirps) %>%
  dplyr::select(est, var, ps_x, subsection, response) %>%
  dplyr::mutate(section = str_remove_all(subsection, "[:lower:]"),
    province = str_sub(section, end = -2))

ps_l <- split(ps_dat, list(ps_dat$province))
```



### Hierarchical Bayesian Modeling

```{r}
# HB Unit
set.seed(1)
bayes_unit <- list()
bayes_unit[1:length(iw)] <- lapply(
  iw,
  hb_unit,
  formula = BIOLIVE_TPA ~ nlcd11,
  small_area = "subsection",
  pop_data = tccpop
)
bayes_unit[(length(iw) + 1):(2 * length(iw))] <-
  lapply(
    iw,
    hb_unit,
    formula = BALIVE_TPA ~ nlcd11,
    small_area = "subsection",
    pop_data = tccpop
  )
bayes_unit[(2 * length(iw) + 1):(3 * length(iw))] <-
  lapply(
    iw,
    hb_unit,
    formula = CNTLIVE_TPA ~ nlcd11,
    small_area = "subsection",
    pop_data = tccpop
  )
bayes_unit[(3 * length(iw) + 1):(4 * length(iw))] <-
  lapply(
    iw,
    hb_unit,
    formula = VOLNLIVE_TPA ~ nlcd11,
    small_area = "subsection",
    pop_data = tccpop
  )

# saveRDS(bayes_unit, "bayes_unit.rds")

res_hbu <- data.frame(
  subsection = names(unlist(lapply(bayes_unit, EST))),
response = c(
    rep("BIOLIVE_TPA", length(post_strat_bio)),
    rep("BALIVE_TPA", length(post_strat_ba)),
    rep("CNTLIVE_TPA", length(post_strat_cnt)),
    rep("VOLNLIVE_TPA", length(post_strat_voln))),
  est_hb_unit = unlist(lapply(bayes_unit, EST)),
  cov_hb_unit = unlist(lapply(bayes_unit, hb_CoV))
)

results <- results %>%
  left_join(res_hbu, by = c("subsection" = "subsection",
                        "response" = "response"))
```

```{r}
# HB Area
set.seed(1)
bayes_area <- list()
bayes_area[1:length(iw)] <-
  lapply(
    iw,
    hb_area,
    formula = BIOLIVE_TPA ~ nlcd11,
    small_area = "subsection",
    pop_data = tccpop
  )
bayes_area[(length(iw) + 1):(2 * length(iw))] <-
  lapply(
    iw,
    hb_area,
    formula = BALIVE_TPA ~ nlcd11,
    small_area = "subsection",
    pop_data = tccpop
  )
bayes_area[(2 * length(iw) + 1):(3 * length(iw))] <-
  lapply(
    iw,
    hb_area,
    formula = CNTLIVE_TPA ~ nlcd11,
    small_area = "subsection",
    pop_data = tccpop
  )
bayes_area[(3 * length(iw) + 1):(4 * length(iw))] <-
  lapply(
    iw,
    hb_area,
    formula = VOLNLIVE_TPA ~ nlcd11,
    small_area = "subsection",
    pop_data = tccpop
  )

# saveRDS(bayes_area, "bayes_area.rds")

aranged_df <- intwest_no0 %>%
  filter(province %in% names(iw)) %>%
  arrange(province) %>%
  arrange(subsection)
hb_area_res <- data.frame(
  subsection = rep(unique(aranged_df$subsection), 4),
  est_hb_area = unlist(lapply(bayes_area, EST)),
  cov_hb_area = unlist(lapply(bayes_area, hb_CoV)),
  response = c(
    rep("BIOLIVE_TPA", length(post_strat_bio)),
    rep("BALIVE_TPA", length(post_strat_ba)),
    rep("CNTLIVE_TPA", length(post_strat_cnt)),
    rep("VOLNLIVE_TPA", length(post_strat_voln))
  )
)

results <- results %>%
  left_join(hb_area_res, by = c("subsection" = "subsection",
                                "response" = "response"))
```


### Frequentist Modeling

```{r}
# Freq Unit
set.seed(1)
frequnit <- list()
frequnit[1:length(iw)] <-
  lapply(iw, freq_unit, formula = BIOLIVE_TPA ~ nlcd11, "subsection", tccpop)
frequnit[(length(iw) + 1):(2 * length(iw))] <-
  lapply(iw, freq_unit, formula = BALIVE_TPA ~ nlcd11, "subsection", tccpop)
frequnit[(2 * length(iw) + 1):(3 * length(iw))] <-
  lapply(iw, freq_unit, formula = CNTLIVE_TPA ~ nlcd11, "subsection", tccpop)
frequnit[(3 * length(iw) + 1):(4 * length(iw))] <-
  lapply(iw, freq_unit, formula = VOLNLIVE_TPA ~ nlcd11, "subsection", tccpop)

# saveRDS(frequnit, "freq_unit.rds")

frequnit_list <- list()
  for(i in 1:(4 * length(iw))) {
    frequnit_list[[i]] <- frequnit[[i]]$eblup
  }

frequnit_df <- frequnit_list %>%
  bind_rows() %>%
  mutate(response = c(
    rep("BIOLIVE_TPA", length(post_strat_bio)),
    rep("BALIVE_TPA", length(post_strat_ba)),
    rep("CNTLIVE_TPA", length(post_strat_cnt)),
    rep("VOLNLIVE_TPA", length(post_strat_voln)))) %>%
  rename(
    subsection = domain,
    est_freq_unit = eblup
  ) %>%
  dplyr::select(-sampsize)

# Coef of variation
frequnitcov <- c()
frequnitcov <- c(
  Reduce(c,
       lapply(iw,
       freq_unit_CoV,
       formula = BIOLIVE_TPA ~ nlcd11,
       small_area = "subsection",
       pop_data = tccpop,
       B = 500)),
  Reduce(c,
       lapply(iw,
       freq_unit_CoV,
       formula = BALIVE_TPA ~ nlcd11,
       small_area = "subsection",
       pop_data = tccpop,
       B = 500)),
  Reduce(c,
       lapply(iw,
       freq_unit_CoV,
       formula = CNTLIVE_TPA ~ nlcd11,
       small_area = "subsection",
       pop_data = tccpop,
       B = 500)),
  Reduce(c,
       lapply(iw,
       freq_unit_CoV,
       formula = VOLNLIVE_TPA ~ nlcd11,
       small_area = "subsection",
       pop_data = tccpop,
       B = 500))
)

frequnitcov_df <- data.frame(
  cov_freq_unit = frequnitcov,
  subsection = names(frequnitcov),
  response = c(
    rep("BIOLIVE_TPA", length(post_strat_bio)),
    rep("BALIVE_TPA", length(post_strat_ba)),
    rep("CNTLIVE_TPA", length(post_strat_cnt)),
    rep("VOLNLIVE_TPA", length(post_strat_voln))
  )
)

frequnit_df <- frequnit_df %>%
  left_join(frequnitcov_df, by = c("subsection" = "subsection",
                                   "response" = "response"))

results <- results %>%
  left_join(frequnit_df, by = c("subsection" = "subsection",
                                   "response" = "response"))
```


```{r}
# Freq Area
set.seed(1)
freqarea <- list()
freqarea[1:length(iw)] <- lapply(iw, freq_area, formula = BIOLIVE_TPA ~ nlcd11, "subsection", tccpop)
freqarea[(length(iw) + 1):(2 * length(iw))] <- lapply(iw, freq_area, formula = BALIVE_TPA ~ nlcd11, "subsection", tccpop)
freqarea[(2 * length(iw) + 1):(3 * length(iw))] <- lapply(iw, freq_area, formula = CNTLIVE_TPA ~ nlcd11, "subsection", tccpop)
freqarea[(3 * length(iw) + 1):(4 * length(iw))] <- lapply(iw, freq_area, formula = VOLNLIVE_TPA ~ nlcd11, "subsection", tccpop)

freqarea_list <- list()
  for(i in 1:(4 * length(iw))) {
    freqarea_list[[i]] <- freqarea[[i]]$est$eblup
  }
freqarea_cov_list <- list()
  for(i in 1:(4 * length(iw))) {
    freqarea_cov_list[[i]] <- sqrt(freqarea[[i]]$mse)
  }

# saveRDS(freqarea, "freq_area.rds")
freq_area_res <- data.frame(
  subsection = rep(unique(aranged_df$subsection), 4),
  est_freq_area = unlist(freqarea_list),
  se_freq_area = unlist(freqarea_cov_list),
  response = c(
    rep("BIOLIVE_TPA", length(post_strat_bio)),
    rep("BALIVE_TPA", length(post_strat_ba)),
    rep("CNTLIVE_TPA", length(post_strat_cnt)),
    rep("VOLNLIVE_TPA", length(post_strat_voln))
  )
)
results <- results %>%
  left_join(freq_area_res,
            by = c("subsection" = "subsection",
                   "response" = "response"))
results <- results %>%
  mutate(cov_freq_area = se_freq_area / est_dirmean)
```

```{r}
# Freq Area CoV (Bootstrap rather than MSE)
## Bootstrapping the post-strat estimates
set.seed(1)
boots <- list()
ps_resamp_list <- list()

for(j in 1:500){
  for(i in 1:length(subsection_list)) {
    boots[[i]] <- sample_n(tbl = subsection_list[[i]],
                           size = length(subsection_list[[i]]$BIOLIVE_TPA), 
                           replace = TRUE)
  }
  ps_resamp_list[[j]] <- boots
}


post_strat_bio_rs <- list()
post_strat_ba_rs <- list()
post_strat_voln_rs <- list()
post_strat_cnt_rs <- list()
res <- list()
for(i in 1:length(ps_resamp_list)) {
  post_strat_bio_rs[[i]] <- map2(.x = ps_resamp_list[[i]], .y = strata_list, .f = postStrat2_bio)
  post_strat_ba_rs[[i]] <- map2(.x = ps_resamp_list[[i]], .y = strata_list, .f = postStrat2_ba)
  post_strat_voln_rs[[i]] <- map2(.x = ps_resamp_list[[i]], .y = strata_list, .f = postStrat2_voln)
  post_strat_cnt_rs[[i]] <- map2(.x = ps_resamp_list[[i]], .y = strata_list, .f = postStrat2_cnt)
}

post_strat_bio_rs_df <- bind_rows(post_strat_bio_rs) %>%
  mutate(subsection = rep(names(subsection_list), 500)) %>%
  mutate(rep = unlist(lapply(1:500, rep, length(post_strat_bio)))) %>%
  mutate(response = rep("BIOLIVE_TPA", 500 * length(post_strat_bio)),
         var = sd^2,
         section = str_remove_all(subsection, "[:lower:]"),
         province = str_sub(section, end = -2))

post_strat_ba_rs_df <- bind_rows(post_strat_ba_rs) %>%
  mutate(subsection = rep(names(subsection_list), 500)) %>%
  mutate(rep = unlist(lapply(1:500, rep, length(post_strat_ba)))) %>%
  mutate(response = rep("BALIVE_TPA", 500 * length(post_strat_ba)),
         var = sd^2,
         section = str_remove_all(subsection, "[:lower:]"),
         province = str_sub(section, end = -2))

post_strat_cnt_rs_df <- bind_rows(post_strat_cnt_rs) %>%
  mutate(subsection = rep(names(subsection_list), 500)) %>%
  mutate(rep = unlist(lapply(1:500, rep, length(post_strat_cnt)))) %>%
  mutate(response = rep("CNTLIVE_TPA", 500 * length(post_strat_cnt)),
         var = sd^2,
         section = str_remove_all(subsection, "[:lower:]"),
         province = str_sub(section, end = -2))

post_strat_voln_rs_df <- bind_rows(post_strat_voln_rs) %>%
  mutate(subsection = rep(names(subsection_list), 500)) %>%
  mutate(rep = unlist(lapply(1:500, rep, length(post_strat_voln)))) %>%
  mutate(response = rep("VOLNLIVE_TPA", 500 * length(post_strat_voln)),
         var = sd^2,
         section = str_remove_all(subsection, "[:lower:]"),
         province = str_sub(section, end = -2))

write.csv(post_strat_bio_rs_df, "post_strat_bio_rs_df.csv")
write.csv(post_strat_ba_rs_df, "post_strat_ba_rs_df.csv")
write.csv(post_strat_cnt_rs_df, "post_strat_cnt_rs_df.csv")
write.csv(post_strat_voln_rs_df, "post_strat_voln_rs_df.csv")

# test <- split(post_strat_voln_rs_df, f = post_strat_voln_rs_df$province)
```

```{r}
tcc <- tccpop %>%
  dplyr::select(zoneid, mean)


## basal
ba_df <- post_strat_ba_rs_df %>%
  inner_join(tcc, by = c("subsection" = "zoneid")) 

ba_l <- split(ba_df, ba_df$rep)

basal <- data.frame()
for(i in 1:500) {
  basal[i,1:length(post_strat_ba)] <- eblupFH(ba_l[[i]]$ps_est ~ ba_l[[i]]$mean, ba_l[[i]]$var)$eblup
}
colnames(basal) <- paste0("a",ba_l[[1]]$subsection)


## bio
bio_df <- post_strat_bio_rs_df %>%
  inner_join(tcc, by = c("subsection" = "zoneid")) 

bio_l <- split(bio_df, bio_df$rep)

biolive <- data.frame()
for(i in 1:500) {
  biolive[i,1:length(post_strat_bio)] <- eblupFH(bio_l[[i]]$ps_est ~ bio_l[[i]]$mean, bio_l[[i]]$var)$eblup
}
colnames(biolive) <- paste0("a",bio_l[[1]]$subsection)


## cnt
cnt_df <- post_strat_cnt_rs_df %>%
  inner_join(tcc, by = c("subsection" = "zoneid")) 

cnt_l <- split(cnt_df, cnt_df$rep)

cnt <- data.frame()
for(i in 1:500) {
  cnt[i,1:length(post_strat_cnt)] <- eblupFH(cnt_l[[i]]$ps_est ~ cnt_l[[i]]$mean, cnt_l[[i]]$var)$eblup
}
colnames(cnt) <- paste0("a",cnt_l[[1]]$subsection)


## voln
voln_df <- post_strat_voln_rs_df %>%
  inner_join(tcc, by = c("subsection" = "zoneid")) 

voln_l <- split(voln_df, voln_df$rep)

voln <- data.frame()
for(i in 1:500) {
  voln[i,1:length(post_strat_voln)] <- eblupFH(voln_l[[i]]$ps_est ~ voln_l[[i]]$mean, voln_l[[i]]$var)$eblup
}
colnames(voln) <- paste0("a",voln_l[[1]]$subsection)


## compute sds
bio_sd <- apply(biolive, 2, sd)
ba_sd <- apply(basal, 2, sd)
cnt_sd <- apply(cnt, 2, sd)
voln_sd <- apply(voln, 2, sd)

### sd dataframe
sd_dataframe <- data.frame(
  sd = c(bio_sd, ba_sd, cnt_sd, voln_sd),
  response = c(rep("BIOLIVE_TPA", length(post_strat_bio)),
               rep("BALIVE_TPA", length(post_strat_ba)),
               rep("CNTLIVE_TPA", length(post_strat_cnt)),
               rep("VOLNLIVE_TPA", length(post_strat_voln))),
  subsection = rep(substr(names(bio_sd), 2, 10), 4)
)

results <- results %>%
  left_join(sd_dataframe, by = c("response" = "response",
                                 "subsection" = "subsection"))
results <- results %>%
  mutate(cov_freq_area_boot = sd / est_dirmean)
results <- results %>%
  rename(sd_freq_area_boot = sd)
```



```{r}
write.csv(results, "final_results.csv")
saveRDS(results, file = "final_results.rds")
```



