---
title: "data-chapter-figures"
author: "Grayson White"
date: "10/22/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(USAboundaries)
library(patchwork)
library(latex2exp)
`%ni%` <- Negate(`%in%`)

interior_west <- c("AZ", "CO", "ID", "MT", "NV", "NM", "UT", "WY")

states <- data.frame(state.abb) %>%
  filter(state.abb %ni% interior_west & state.abb %ni% c("AK", "HI")) %>%
  pull()

dat_small <- read_csv("../../data/subsets/dat_small.csv")
```

This document includes the R code needed to create the figures in the data chapter. 

```{r, message = FALSE, warning = FALSE, fig.align="center", fig.retina=4}
# R Code for generating the int west on USA
ggplot() +
  geom_sf(data = us_boundaries(type = "state",
                               states = interior_west),
          fill = "#2A5043",
          color = "black") +
  geom_sf(data = us_boundaries(type = "state",
                               states = states),
          fill = "#A9A9A9",
          color = "black") +
  theme_void()
```

```{r, message = FALSE, warning = FALSE, fig.retina = 4, fig.align = 'center', fig.height=4, fig.width=6}
# R Code for creating the summary stat maps
subsections <- st_read("../../data/SA_eco_subsection/SA_eco_subsection.shp", quiet = TRUE)

subsections1 <- subsections %>%
  filter(SUBSECT %in% dat_small$subsection)

int_west_sf <- us_boundaries(type = "state",
                         states = interior_west)

intersection <- st_intersection(int_west_sf, subsections1)

dat_summary <- dat_small %>%
  group_by(subsection) %>%
  summarize(mean_bio = mean(BIOLIVE_TPA),
            mean_cnt = mean(CNTLIVE_TPA),
            mean_vol = mean(VOLNLIVE_TPA),
            mean_bas = mean(BALIVE_TPA),
            mean_nlcd = mean(nlcd11))

intersection <- left_join(intersection, dat_summary, by = c("SUBSECT" = "subsection"))

plot1 <- ggplot() +
  geom_sf(data = intersection,
          mapping = aes(fill = mean_bio)) +
  geom_sf(data = us_boundaries(type = "state",
                               states = interior_west),
          color = "black",
          alpha = 0,
          size = 0.25) +
  scale_fill_gradient2(high = "#2A5043",
                       mid = "#80BCA2",
                       low = "#FBE1BB",
                       midpoint = 30) +
  theme_void() +
  labs(fill = TeX("Mean Biomass (lbs)")) +
  theme(legend.key.size = unit(1.05, "cm"),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14))

plot2 <- ggplot() +
  geom_sf(data = intersection,
          mapping = aes(fill = mean_cnt)) +
  geom_sf(data = us_boundaries(type = "state",
                               states = interior_west),
          color = "black",
          alpha = 0,
          size = 0.25) +
  scale_fill_gradient2(high = "#2A5043",
                       mid = "#80BCA2",
                       low = "#FBE1BB",
                       midpoint = 400) +
  theme_void() +
  labs(fill = "Mean Tree Count\n(trees/acre)") +
  theme(legend.key.size = unit(1.05, "cm"),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14))

plot3 <- ggplot() +
  geom_sf(data = intersection,
          mapping = aes(fill = mean_vol)) +
  geom_sf(data = us_boundaries(type = "state",
                               states = interior_west),
          color = "black",
          alpha = 0,
          size = 0.25) +
  scale_fill_gradient2(high = "#2A5043",
                       mid = "#80BCA2",
                       low = "#FBE1BB",
                       midpoint = 1750) +
  theme_void() +
  labs(fill = TeX("Mean Volume (ft$^3$)")) +
  theme(legend.key.size = unit(1.05, "cm"),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14))

plot4 <- ggplot() +
  geom_sf(data = intersection,
          mapping = aes(fill = mean_bas)) +
  geom_sf(data = us_boundaries(type = "state",
                               states = interior_west),
          color = "black",
          alpha = 0,
          size = 0.25) +
  scale_fill_gradient2(high = "#2A5043",
                       mid = "#80BCA2",
                       low = "#FBE1BB",
                       midpoint = 77) +
  theme_void() +
  labs(fill = TeX("Mean Basal Area (ft$^2$)")) +
  theme(legend.key.size = unit(1.05, "cm"),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14))

plot5 <- ggplot() +
  geom_sf(data = intersection,
          mapping = aes(fill = mean_nlcd)) +
  geom_sf(data = us_boundaries(type = "state",
                               states = interior_west),
          color = "black",
          alpha = 0,
          size = 0.25) +
  scale_fill_gradient2(high = "#2A5043",
                       mid = "#80BCA2",
                       low = "#FBE1BB",
                       midpoint = 30) +
  theme_void() +
  labs(fill = TeX("Mean Percent\nCanopy Cover")) +
  theme(legend.key.size = unit(1.05, "cm"),
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14))

# ggsave("biomass_new.png", plot1)
# ggsave("count_new.png", plot2)
# ggsave("voln_new.png", plot3)
# ggsave("basal_new.png", plot4)
# ggsave("nlcd_new.png", plot5)
```



