---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE}
library(rstan)
library(rstanarm)
library(tidyverse)
```


```{r}
m333 <- read_csv("../data/subsets/dat_small.csv") %>%
  filter(province == "M333")

mod <- stan_lmer(BIOLIVE_TPA ~ 1 + nlcd11 + (1 | subsection),
                 data = m333,
                 verbose = FALSE)

mod_poly <- stan_lmer(BIOLIVE_TPA ~ 1 + poly(nlcd11, 2) + (1 | subsection),
                 data = m333,
                 verbose = FALSE)

# ggplot(m333, aes(x = nlcd11,
#                  y = BIOLIVE_TPA)) +
#   geom_point() +
#   facet_wrap(~subsection)


mod_df <- data.frame(
  fitted = mod$fitted.values,
  subsection = m333 %>% dplyr::select(subsection),
  true = mod$y
)

mod_df_poly <- data.frame(
  fitted = mod_poly$fitted.values,
  subsection = m333 %>% dplyr::select(subsection),
  true = mod_poly$y
)

mod_df %>%
  yardstick::metrics(truth = true,
                     estimate = fitted)

sub_mean <- mod_df %>%
  group_by(subsection) %>%
  summarize(mean_y = mean(true))

bayes_cv <- mod_df %>%
  group_by(subsection) %>%
  yardstick::rmse(truth = true,
                  estimate = fitted) %>%
  left_join(sub_mean) %>%
  group_by(subsection) %>%
  summarize(cv = .estimate / mean_y)

mod_df %>%
  group_by(subsection) %>%
  summarize(direct_cv = sd(true) / mean(true)) %>%
  left_join(bayes_cv) %>%
  mutate(subsection = fct_reorder(subsection, direct_cv)) %>%
  ggplot(aes(x = subsection)) +
  geom_point(aes(y = cv, color = "goldenrod")) +
  geom_point(aes(y = direct_cv, color = "forestgreen")) +
  theme_bw() +
  scale_color_manual(
    name = 'Estimate Type',
    values = c('goldenrod' = 'goldenrod',
               'forestgreen' = 'forestgreen'),
    labels = c('Direct (Mean)', 'Hierarchical Bayesian'),
    guide = "legend"
  ) +
  theme(axis.text.x = element_text(
    angle = 90,
    vjust = 0.5,
    hjust = 1
  ),
  legend.position = "bottom") +
  labs(x = "Subsection",
       y = "Coeffcient of Variation")

mod_df %>%
  group_by(subsection) %>%
  summarize(mean_direct = mean(true),
            mean_bayes = mean(fitted)) %>%
  mutate(subsection = fct_reorder(subsection, mean_direct)) %>%
  ggplot(aes(x = subsection)) +
  geom_point(aes(y = mean_bayes,
                 color = "goldenrod"),
             position = position_nudge(x = -0.1)) + 
  geom_point(aes(y = mean_direct,
                 color = "forestgreen"),
             position = position_nudge(x = 0.1)) +
  theme_bw() +
  scale_color_manual(
    name = 'Estimate Type',
    values = c('goldenrod' = 'goldenrod',
               'forestgreen' = 'forestgreen'),
    labels = c('Direct (Mean)', 'Hierarchical Bayesian'),
    guide = "legend"
  ) +
  theme(axis.text.x = element_text(
    angle = 90,
    vjust = 0.5,
    hjust = 1
  ),
  legend.position = "bottom") +
  labs(x = "Subsection",
       y = "Estimate")
  

ggplot(data = mod_df,
       aes(x = fitted,
           y = true)) +
  geom_point()
```


## All the provinces

```{r}
df <- read_csv("../data/subsets/dat_small.csv")
df <- df %>%
  mutate(id = province) %>%
  group_by(id) %>%
  nest()

models_df <- list()
cv <- c()
models <- readRDS("models.rds")
for(i in 1:14) {
  # models[[i]] <- stan_lmer(BIOLIVE_TPA ~ 1 + nlcd11 + (1 | subsection),
  #                data = df[[i,2]][[1]],
  #                verbose = FALSE)
  
  models_df[[i]] <- data.frame(
  fitted = models[[i]]$fitted.values,
  subsection = df[[i,2]][[1]] %>% dplyr::select(subsection),
  true = models[[i]]$y
  ) }


cv <- list()
for(i in 1:14){

cv[i] <- models_df[[i]] %>%
  group_by(subsection) %>%
  summarize(bayes_cv = sd(fitted, na.rm = TRUE) / mean(fitted, na.rm = TRUE),
            direct_cv = sd(true, na.rm = TRUE) / mean(true, na.rm = TRUE)) %>%
 summarize(median(bayes_cv / direct_cv, na.rm = TRUE))
}
unlist(cv)
mean(unlist(cv))

```



